-- AlterTable
ALTER TABLE "Tenant" ADD COLUMN     "gracePeriodMinutes" INTEGER NOT NULL DEFAULT 15,
ADD COLUMN     "pettyCashCapNpr" INTEGER NOT NULL DEFAULT 20000,
ADD COLUMN     "vatRate" DOUBLE PRECISION NOT NULL DEFAULT 13;
