// tailwind.config.cjs
module.exports = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx,html}'],
  theme: {
    extend: {
      colors: {
        'surface-container-lowest': '#ffffff',
        'on-error': '#ffffff',
        'surface': '#fbf8ff',
        'primary-fixed': '#dee0ff',
        'on-primary-container': '#cacfff',
        'inverse-primary': '#bac3ff',
        'secondary-fixed-dim': '#67d9c9',
        'error': '#ba1a1a',
        'on-primary-fixed-variant': '#293ca0',
        'surface-tint': '#4355b9',
        'tertiary-fixed-dim': '#ffb784',
        'surface-dim': '#dbd9e2',
        'surface-bright': '#fbf8ff',
        'outline': '#757684',
        'on-tertiary-fixed': '#301400',
        'tertiary-fixed': '#ffdcc6',
        'secondary-container': '#85f6e5',
        'tertiary-container': '#8f4700',
        'inverse-surface': '#2f3037',
        'secondary-fixed': '#85f6e5',
        'on-surface-variant': '#454652',
        'primary-container': '#3f51b5',
        'error-container': '#ffdad6',
        'secondary': '#006a60',
        'inverse-on-surface': '#f2eff9',
        'on-tertiary-container': '#ffc7a2',
        'tertiary': '#6c3400',
        'background': '#fbf8ff',
        'on-primary-fixed': '#00105c',
        'on-secondary': '#ffffff',
        'surface-container': '#efedf6',
        'surface-container-low': '#f4f2fc',
        'on-surface': '#1a1b22',
        'on-background': '#1a1b22',
        'on-secondary-fixed': '#00201c',
        'on-secondary-container': '#007166',
        'primary-fixed-dim': '#bac3ff',
        'on-secondary-fixed-variant': '#005048',
        'surface-container-high': '#e9e7f0',
        'on-error-container': '#93000a',
        'on-primary': '#ffffff',
        'on-tertiary': '#ffffff',
        'primary': '#24389c',
        'surface-variant': '#e3e1ea',
        'surface-container-highest': '#e3e1ea',
        'on-tertiary-fixed-variant': '#713700',
        'outline-variant': '#c5c5d4',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        lg: '24px',
        gutter: '16px',
        xs: '4px',
        'margin-desktop': '24px',
        md: '16px',
        base: '8px',
        sm: '8px',
        'margin-mobile': '16px',
        xl: '32px',
      },
      fontFamily: {
        'label-md': ['Roboto'],
        h1: ['Roboto'],
        h2: ['Roboto'],
        h4: ['Roboto'],
        'body-md': ['Roboto'],
        'body-lg': ['Roboto'],
        'label-sm': ['Roboto'],
        h3: ['Roboto'],
        'h1-mobile': ['Roboto'],
      },
      fontSize: {
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '500' }],
        h1: ['34px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        h2: ['24px', { lineHeight: '32px', fontWeight: '600' }],
        h4: ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['10px', { lineHeight: '12px', fontWeight: '700' }],
        h3: ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'h1-mobile': ['28px', { lineHeight: '34px', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};
