import { useState } from 'react';
import type { FormEvent, ReactNode } from 'react';
import { useLocation } from 'react-router-dom';
import { Button } from '../components/ui/Button';
import { Card } from '../components/ui/Card';
import { StatusBadge } from '../components/ui/StatusBadge';
import { api } from '../services/api';

const field = { width: '100%', minHeight: 44, padding: '10px 12px', borderRadius: 10, border: '1px solid var(--color-border, rgba(21,96,189,.2))', background: 'var(--color-surface, #fff)', color: 'var(--color-text)' } as const;
const label = { display: 'grid', gap: 6, fontSize: 13, fontWeight: 700, color: 'var(--color-text)' } as const;
const form = { display: 'grid', gap: 16 } as const;

function Page({ title, description, children }: { title: string; description: string; children: ReactNode }) {
  return <main style={{ maxWidth: 960, margin: '0 auto', display: 'grid', gap: 20 }}>
    <header><h1 style={{ fontSize: 24, color: 'var(--color-text)' }}>{title}</h1><p style={{ marginTop: 6, color: 'var(--color-text-muted, rgba(44,62,80,.7))' }}>{description}</p></header>
    {children}
  </main>;
}

function Feedback({ message, error }: { message: string; error: string }) {
  if (!message && !error) return null;
  return <div role="status" style={{ padding: 12, borderRadius: 10, background: error ? 'var(--color-error-soft, #fff0f0)' : 'var(--color-success-soft, #eaf8f0)', color: error ? 'var(--color-error)' : 'var(--color-success)', fontWeight: 700 }}>{error || message}</div>;
}

function useAction() {
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const run = async (action: () => Promise<unknown>, success: string) => { setBusy(true); setError(''); setMessage(''); try { await action(); setMessage(success); } catch (cause) { setError(cause instanceof Error ? cause.message : 'The action could not be completed. Try again.'); } finally { setBusy(false); } };
  return { busy, message, error, run };
}

function Approvals() {
  const action = useAction(); const [id, setId] = useState(''); const [reason, setReason] = useState(''); const [kind, setKind] = useState<'leave' | 'petty'>('leave'); const [decision, setDecision] = useState<'APPROVE' | 'REJECT'>('APPROVE');
  const submit = (event: FormEvent) => { event.preventDefault(); if (decision === 'REJECT' && !reason.trim()) return; void action.run(() => kind === 'leave' ? api.branchAdmin.decideLeave(id, decision, reason) : decision === 'APPROVE' ? api.finances.approvePettyCash(id, 'APPROVE_L1', reason) : api.finances.decidePettyCash(id, 'REJECT', reason), kind === 'leave' ? 'Leave decision recorded with the correct approval level.' : 'Petty cash Level 1 decision recorded; funds were not released.'); };
  const reasonMissing = decision === 'REJECT' && !reason.trim();
  return <Page title="Approvals" description="Finalize casual and early-out leave, or advance long sick leave and petty cash to Tenant Admin."><Card hoverable={false}><form onSubmit={submit} style={form} aria-busy={action.busy}>
    <label style={label} htmlFor="approval-kind">Request type<select id="approval-kind" value={kind} onChange={e => setKind(e.target.value as 'leave' | 'petty')} style={field}><option value="leave">Staff leave</option><option value="petty">Petty cash</option></select></label>
    <label style={label} htmlFor="approval-id">Request ID (required)<input id="approval-id" required value={id} onChange={e => setId(e.target.value)} style={field} /></label>
    <label style={label} htmlFor="approval-decision">Decision<select id="approval-decision" value={decision} onChange={e => setDecision(e.target.value as 'APPROVE' | 'REJECT')} style={field}><option value="APPROVE">Approve</option><option value="REJECT">Reject</option></select></label>
    <label style={label} htmlFor="approval-reason">Reason {decision === 'REJECT' ? '(required)' : '(optional)'}<textarea id="approval-reason" value={reason} onChange={e => setReason(e.target.value)} aria-invalid={reasonMissing || undefined} aria-describedby={reasonMissing ? 'approval-reason-error' : undefined} style={{ ...field, minHeight: 84 }} />{reasonMissing && <span id="approval-reason-error" style={{ color: 'var(--color-error)', fontWeight: 600 }}>Enter a reason before rejecting this request.</span>}</label>
    <Feedback message={action.message} error={action.error} /><Button type="submit" disabled={action.busy || !id.trim() || reasonMissing}>{action.busy ? 'Saving decision…' : 'Save decision'}</Button>
  </form></Card></Page>;
}

function StudentExceptions() {
  const action = useAction(); const [mode, setMode] = useState<'departure' | 'remark' | 'fee'>('departure'); const [studentId, setStudentId] = useState(''); const [branchId, setBranchId] = useState(''); const [text, setText] = useState(''); const [collector, setCollector] = useState(''); const [parentVisible, setParentVisible] = useState(false); const [scope, setScope] = useState<'ONE_SESSION' | 'ONE_DAY'>('ONE_SESSION');
  const submit = (event: FormEvent) => { event.preventDefault(); if (!text.trim()) return; const request = mode === 'departure' ? api.branchAdmin.emergencyDeparture({ studentId, branchId, reason: text, collectedBy: collector, departureTime: new Date().toISOString() }) : mode === 'remark' ? api.branchAdmin.addRemark({ studentId, subject: 'Administrative remark', message: text, parentVisible }) : api.branchAdmin.grantFeeOverride({ studentId, branchId, scope, reason: text }); void action.run(() => request, mode === 'departure' ? 'Departure permanently recorded and the parent notification was sent.' : mode === 'remark' ? 'Remark saved with your identity and timestamp.' : 'Temporary access granted and added to fee-status history.'); };
  return <Page title="Student exceptions" description="Record attributable exceptions. Fee-block access remains scoped and never becomes a permanent unblock."><Card hoverable={false}><form onSubmit={submit} style={form} aria-busy={action.busy}>
    <label style={label} htmlFor="exception-type">Action<select id="exception-type" value={mode} onChange={e => setMode(e.target.value as 'departure' | 'remark' | 'fee')} style={field}><option value="departure">Emergency departure</option><option value="fee">Temporary fee access</option><option value="remark">Administrative remark</option></select></label>
    <label style={label} htmlFor="exception-student">Student ID (required)<input id="exception-student" required value={studentId} onChange={e => setStudentId(e.target.value)} style={field} /></label>
    {mode !== 'remark' && <label style={label} htmlFor="exception-branch">Branch ID (required)<input id="exception-branch" required value={branchId} onChange={e => setBranchId(e.target.value)} style={field} /></label>}
    {mode === 'departure' && <label style={label} htmlFor="exception-collector">Collected by (optional)<input id="exception-collector" value={collector} onChange={e => setCollector(e.target.value)} autoComplete="name" style={field} /></label>}
    {mode === 'fee' && <label style={label} htmlFor="override-scope">Access scope<select id="override-scope" value={scope} onChange={e => setScope(e.target.value as 'ONE_SESSION' | 'ONE_DAY')} style={field}><option value="ONE_SESSION">One session</option><option value="ONE_DAY">One day</option></select></label>}
    <label style={label} htmlFor="exception-reason">{mode === 'departure' ? 'Departure reason' : mode === 'fee' ? 'Override reason' : 'Remark'} (required)<textarea id="exception-reason" required value={text} onChange={e => setText(e.target.value)} style={{ ...field, minHeight: 96 }} /></label>
    {mode === 'remark' && <label style={{ display: 'flex', alignItems: 'center', gap: 10, minHeight: 44 }}><input type="checkbox" checked={parentVisible} onChange={e => setParentVisible(e.target.checked)} />Visible to parents</label>}
    <Feedback message={action.message} error={action.error} /><Button type="submit" disabled={action.busy || !studentId.trim() || !text.trim()}>{action.busy ? 'Recording…' : mode === 'departure' ? 'Record and notify parent' : mode === 'fee' ? 'Grant temporary access' : 'Save remark'}</Button>
  </form></Card><Card hoverable={false}><h2 style={{ fontSize: 18 }}>Fee override safeguards</h2><p style={{ marginTop: 8, color: 'var(--color-text-muted, rgba(44,62,80,.7))' }}>Every override records its reason, scope, expiry, and granting admin in visible fee-status history.</p><StatusBadge variant="info">Permanent unblock unavailable</StatusBadge></Card></Page>;
}

function CreateForm({ type }: { type: 'class' | 'calendar' | 'certificate' }) {
  const action = useAction(); const [values, setValues] = useState<Record<string, string>>({}); const set = (key: string) => (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => setValues(v => ({ ...v, [key]: event.target.value }));
  const submit = (event: FormEvent) => { event.preventDefault(); const request = type === 'class' ? api.branchAdmin.createPersonalizedClass({ branchId: values.branchId, name: values.name, courseId: values.courseId, schedule: { description: values.schedule }, feeStructure: { mode: values.feeMode, amountNpr: values.fee } }) : type === 'calendar' ? api.branchAdmin.createCalendarEvent({ branchId: values.branchId, title: values.name, description: values.details, eventType: 'OTHER', startDate: values.startDate, endDate: values.endDate }) : api.branchAdmin.issueCertificate({ studentId: values.studentId, templateId: values.templateId, branchId: values.branchId }); void action.run(() => request, type === 'class' ? 'Personalized class created. Add students using its independent enrollment record.' : type === 'calendar' ? 'Branch event added. Tenant-wide events remain unchanged.' : 'Certificate generated and logged in student history.'); };
  const title = type === 'class' ? 'Personalized classes' : type === 'calendar' ? 'Branch calendar' : 'Certificates';
  return <Page title={title} description={type === 'class' ? 'Create a 1:1 or small-group class with its own fee, attendance, and homework stream.' : type === 'calendar' ? 'Layer branch events over the read-only tenant calendar.' : 'Issue from a Tenant Admin-owned master template; its fields and layout remain locked.'}><Card hoverable={false}><form onSubmit={submit} style={form} aria-busy={action.busy}>
    <label style={label}>Branch ID (required)<input required value={values.branchId || ''} onChange={set('branchId')} style={field} /></label>
    {type === 'class' && <><label style={label}>Class name (required)<input required value={values.name || ''} onChange={set('name')} style={field} /></label><label style={label}>Course/subject ID (required)<input required value={values.courseId || ''} onChange={set('courseId')} style={field} /></label><label style={label}>Teacher and schedule (required)<textarea required value={values.schedule || ''} onChange={set('schedule')} style={{ ...field, minHeight: 80 }} /></label><label style={label}>Fee model<select value={values.feeMode || 'PER_SESSION'} onChange={set('feeMode')} style={field}><option value="PER_SESSION">Per session</option><option value="FIXED_PACKAGE">Fixed package</option></select></label><label style={label}>Fee in NPR (required)<input required inputMode="decimal" value={values.fee || ''} onChange={set('fee')} style={field} /></label></>}
    {type === 'calendar' && <><label style={label}>Event title (required)<input required value={values.name || ''} onChange={set('name')} style={field} /></label><label style={label}>Starts (required)<input required type="datetime-local" value={values.startDate || ''} onChange={set('startDate')} style={field} /></label><label style={label}>Ends (required)<input required type="datetime-local" value={values.endDate || ''} onChange={set('endDate')} style={field} /></label><label style={label}>Details<textarea value={values.details || ''} onChange={set('details')} style={{ ...field, minHeight: 80 }} /></label></>}
    {type === 'certificate' && <><label style={label}>Student ID (required)<input required value={values.studentId || ''} onChange={set('studentId')} style={field} /></label><label style={label}>Master template ID (required)<input required value={values.templateId || ''} onChange={set('templateId')} style={field} /></label><p style={{ color: 'var(--color-text-muted, rgba(44,62,80,.7))' }}>Branch name, address, and logo are applied automatically. Master template editing is unavailable to Branch Admins.</p></>}
    <Feedback message={action.message} error={action.error} /><Button type="submit" disabled={action.busy}>{action.busy ? 'Saving…' : type === 'certificate' ? 'Generate certificate PDF' : 'Create'}</Button>
  </form></Card></Page>;
}

function ResourceTasks() { const action = useAction(); const [branchId, setBranchId] = useState(''); const [taskId, setTaskId] = useState(''); return <Page title="Resource and maintenance" description="Action-required logs auto-assign maintenance staff; escalated tasks remain visible for direct follow-up."><Card hoverable={false}><div style={form}><label style={label}>Branch ID<input value={branchId} onChange={e => setBranchId(e.target.value)} style={field} /></label><label style={label}>Task ID<input value={taskId} onChange={e => setTaskId(e.target.value)} style={field} /></label><Feedback message={action.message} error={action.error} /><Button disabled={action.busy || !taskId.trim()} onClick={() => void action.run(() => api.branchAdmin.completeMaintenanceTask(taskId), 'Task marked complete with actor and timestamp recorded.')}>Complete task</Button></div></Card><Card hoverable={false}><h2 style={{ fontSize: 18 }}>Escalation policy</h2><p style={{ marginTop: 8, color: 'var(--color-text-muted, rgba(44,62,80,.7))' }}>Tasks unresolved after the Tenant Admin-configured threshold are marked escalated. Default assignment remains branch-scoped.</p><StatusBadge variant="warning">Requires follow-up</StatusBadge></Card></Page>; }

function Drafting() { const action = useAction(); const [branchId, setBranchId] = useState(''); const [text, setText] = useState(''); const [platform, setPlatform] = useState('Facebook'); const [proposedTime, setProposedTime] = useState(''); const submit = (event: FormEvent) => { event.preventDefault(); void action.run(() => api.branchAdmin.createSocialDraft({ branchId, text, platforms: [platform], mediaUrls: [], proposedTime: proposedTime || undefined }), 'Draft submitted to Tenant Admin. Nothing was published.'); }; return <Page title="Social media drafts" description="Prepare branch posts for Tenant Admin approval. Branch Admins cannot publish directly."><Card hoverable={false}><form onSubmit={submit} style={form} aria-busy={action.busy}><label style={label}>Branch ID (required)<input required value={branchId} onChange={e => setBranchId(e.target.value)} style={field} /></label><label style={label}>Post text (required)<textarea required value={text} onChange={e => setText(e.target.value)} style={{ ...field, minHeight: 112 }} /></label><label style={label}>Target platform<select value={platform} onChange={e => setPlatform(e.target.value)} style={field}><option>Facebook</option><option>Instagram</option><option>LinkedIn</option></select></label><label style={label}>Proposed schedule<input type="datetime-local" value={proposedTime} onChange={e => setProposedTime(e.target.value)} style={field} /></label><Feedback message={action.message} error={action.error} /><Button type="submit" disabled={action.busy || !text.trim() || !branchId.trim()}>{action.busy ? 'Submitting…' : 'Submit for approval'}</Button><Button disabled variant="outline">Direct publishing unavailable</Button></form></Card></Page>; }

export function BranchAdminWorkspace() { const path = useLocation().pathname; if (path.includes('leave-requests') || path.includes('petty-cash')) return <Approvals />; if (path.includes('students') || path.includes('fees')) return <StudentExceptions />; if (path.includes('personalized-classes')) return <CreateForm type="class" />; if (path.includes('resource-logs')) return <ResourceTasks />; if (path.includes('certificates')) return <CreateForm type="certificate" />; if (path.includes('academic-calendar')) return <CreateForm type="calendar" />; if (path.includes('social-media') || path.includes('announcements')) return <Drafting />; return <Page title="Branch operations" description="This workspace is limited to your assigned physical branch."><Card hoverable={false}>Choose a branch operation from the navigation.</Card></Page>; }
